name: Deploy to Azure

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{secrets.TEAM3_SERVICE_PRINCIPAL}}'

      - name: Deploy ARM Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: '${{evn.TEAM3_RESOURCE_GROUP_NAME}}'