name: First Workflow

on:
    push:
        branches:
            - main
            

jobs:
    job1:
        runs-on: ubuntu-latest
        env:
          MY_Variable: "This is my variable"

        steps:
            - name: Step 1
              run: echo "step1, ${{ env.MY_Variable }}"
      
            - name: Step 2
              run: echo "step2"
    job2:
                runs-on: ubuntu-latest
            
                steps:
                    - name: Update System Step
                      run: sudo apt-get update