name: First Workflow

on:
 workflow_dispatch:
  inputs:
    name:
      description: 'Name of the person to greet'
      required: true
      default: 'Mona'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "step1"

      - name: Step 2
        run: echo "step2"

